Add blur feature
Fotographia/fotographia-editor pull request #14
Opened 2021-04-03 13:17 UTC by sophia-ts

Closes #5

`Note:`  Ονόμασα την function στη javascript `blurImage` γιατί η blur είναι δεσμευμένη λέξη.

2021-04-04 15:54 UTC, p18mili1 approved these changes

2021-04-05 11:25 UTC, Stavrospanakakis commented on utils/blur.py
> +    return blur
Νομίζω πως δεν χρειάζεται το ```return blur```

2021-04-05 11:26 UTC, Stavrospanakakis requested changes
Αν μπορείς στο commit σου κάνε format τον python κώδικα σου με τα pre-commit hooks

2021-04-05 11:38 UTC, sophia-ts commented on utils/blur.py
> +    return blur
Το έφτιαξα!

2021-04-05 11:40 UTC, Stavrospanakakis approved these changes

2021-04-05 16:25 UTC, dimpram requested changes
Έχεις ένα μικρό conflict αλλά όλα κομπλέ

2021-04-05 16:32 UTC, sophia-ts commented
@dimpram
> Έχεις ένα μικρό conflict αλλά όλα κομπλέ
 

Ναι, συνέβει από το merge του νέου feature. Μόλις το έφτιαξα

2021-04-05 16:57 UTC, dimpram approved these changes

2021-04-05 16:58 UTC, merged