Add flip
Fotographia/fotographia-editor pull request #20
Opened 2021-04-08 10:47 UTC by Stavrospanakakis

Closes #19

2021-04-08 14:27 UTC, dimpram commented
Το δοκίμασα και μου κάνει flip μόνο στον άξονα X'X. Μήπως να το κάναμε σαν drop down κια να είναι και για Y'Y?

2021-04-08 23:05 UTC, p18mili1 commented
@dimpram  Εμένα μου κάνει στον κατακόρυφο άξονα. Μια ιδέα επίσης θα ήταν δυο κουμπιά flip L και flip R

2021-04-09 12:15 UTC, sophia-ts approved these changes

2021-04-09 12:31 UTC, Stavrospanakakis commented
@dimpram  @p18mili1 Όσον αφορά τους άξονες το έκανα έτσι γιατί πίστευα ότι θα βάζαμε το feature mirror για τον άξονα YY'. Αν θέλετε όμως το προσθέτω. Πείτε μου τι πιστεύετε και το φτιάχνω.

2021-04-09 14:02 UTC, dimpram commented
> @dimpram @p18mili1 Όσον αφορά τους άξονες το έκανα έτσι γιατί πίστευα ότι θα βάζαμε το feature mirror για τον άξονα YY'. Αν θέλετε όμως το προσθέτω. Πείτε μου τι πιστεύετε και το φτιάχνω.

Συνήθως είναι στο ίδιο σημείο και με το ίδιο όνομα αυτά οπότε αν θες/μπορείς κάνε το με 2 κουμπιά Flip= { dropdown: horizontally, vertically }

2021-04-09 14:05 UTC, p18mili1 commented
@Stavrospanakakis Έχεις δίκιο, το είχαμε πει. Νομίζω τότε ας έχουμε Η-flip και V-flip.

2021-04-12 10:57 UTC, dimpram commented
Εν τέλει τι γίνεται εδώ με  τα κούμπια

2021-04-12 12:52 UTC, dimpram requested changes

2021-04-12 12:52 UTC, dimpram commented on app.py
> +    flip(path, select_val)
Μου πετάει error γιατί περνάς dictionary ή τέλος πάτνων json στην συνάρτηση flip ενώ κανονικά δέχεται integer. 

Example solution:

```
data = request.get_json("val")
select_val = data["val"]
```

2021-04-12 23:15 UTC, p18mili1 commented
> 
> 
> Εν τέλει τι γίνεται εδώ με τα κούμπια

Ας μείνει το flip μόνο του. Eχω ήδη προσθέσει στα todo το mirror.
`Πρόταση:` Μπορούμε να βάλουμε και μια μικρή περιγραφή στην τελική για κάθε λειτουργία. Όπως ανοίγουν περαιτέρω επιλογές στα resize, gamma και crop, στα one-click functions να εμφανίζεται η περιγραφή με το 1ο κλικ και να εκτελείται με το 2ο.

2021-04-13 07:05 UTC, dimpram commented
@p18mili1 αυτό μπορούμε να το κάνουμε όταν θα πηγαίνει το ποντίκι από πάνω να εμφανίζει μια μικρή περιγραφή.

2021-04-13 08:41 UTC, Stavrospanakakis commented on app.py
> +    flip(path, select_val)
Δεν ξέρω τι γίνεται. Όταν το έτρεχα για κάποιο λόγο δούλευε κανονικά. Anyway. Το έφτιαξα. [commit](https://github.com/Fotographia/fotographia-editor/pull/20/commits/f8bf76cca91cbb160214a97afc9322343e80aeac)

2021-04-13 08:56 UTC, p18mili1 approved these changes

2021-04-13 12:43 UTC, dimpram approved these changes

2021-04-13 12:43 UTC, merged