Feature/rotate
Fotographia/fotographia-editor pull request #22
Opened 2021-04-08 10:56 UTC by Stavrospanakakis

Closes #21

2021-04-08 14:35 UTC, dimpram requested changes
Το rotate δεν κάνει update το resolution

2021-04-09 00:08 UTC, p18mili1 commented
Όντως, έχει δίκιο ο @dimpram αλλά το rotation γίνεται μια χαρά. 
Πρόταση: μήπως να ειχε δυο κουμπά, πάλι rotate L και rotate R, έτσι ώστε ένα κατά λάθος κλικ να μην κοστίζει αλλά 3 προκειμένου να έρθει η εικόνα στη σωστή θέση;

2021-04-09 12:19 UTC, sophia-ts requested changes
Την ίδια παρατήρηση με τον Δημήτρη. (Δηλαδή πως δεν γίνεται update το resolution)

2021-04-09 12:32 UTC, Stavrospanakakis commented
> Το rotate δεν κάνει update το resolution

@dimpram Oops. Το έχω κάνει implement στο flip. Όταν γίνει merged το flip θα το πάρω από εκεί

2021-04-09 12:33 UTC, Stavrospanakakis commented
> Όντως, έχει δίκιο ο @dimpram αλλά το rotation γίνεται μια χαρά.
> Πρόταση: μήπως να ειχε δυο κουμπά, πάλι rotate L και rotate R, έτσι ώστε ένα κατά λάθος κλικ να μην κοστίζει αλλά 3 προκειμένου να έρθει η εικόνα στη σωστή θέση;

Δεν ξέρω. Νομίζω θα γίνει πιο περίπλοκο από ότι χρειάζεται.

2021-04-09 14:04 UTC, dimpram commented
> > Το rotate δεν κάνει update το resolution
> 
> @dimpram Oops. Το έχω κάνει implement στο flip. Όταν γίνει merged το flip θα το πάρω από εκεί

Άρα να κάνουμε πρώτα merge το flip όποτε είναι έτοιμο πρώτα, σωστά?

2021-04-12 23:04 UTC, p18mili1 approved these changes

2021-04-12 23:25 UTC, p18mili1 commented
Θα μπορούσαμε να βάλουμε επιπλέον χαρακτηριστικό το custom rotation

2021-04-13 12:43 UTC, dimpram commented
@Stavrospanakakis αρα τώρα προχωράμε με αυτό φαντάζομαι

2021-04-13 21:18 UTC, dimpram commented
@Stavrospanakakis εξακολουθεί να μην κάνει update το resolution αλλα μπορούμε να το δούμε σε δεύτερη φάση γιατί έχω την εντύπωση οτι φταίει γενικά η υλοποίηση του resolution feature

2021-04-13 21:18 UTC, dimpram approved these changes

2021-04-14 14:11 UTC, sophia-ts approved these changes

2021-04-14 14:12 UTC, merged