Add gamma correction feature
Fotographia/fotographia-editor pull request #23
Opened 2021-04-08 11:58 UTC by sophia-ts

Closes #15

2021-04-08 14:39 UTC, dimpram approved these changes

2021-04-09 00:23 UTC, p18mili1 requested changes

2021-04-09 00:23 UTC, p18mili1 commented on templates/includes/gamma_correction.html
> +        <button type="submit">Camma Correction</button>
Διόρθωσε το Camma. Στη σελίδα είναι ανεπαίσθητη η διαφορά δεν φαίνεται με την πρώτη

2021-04-09 00:25 UTC, p18mili1 commented on templates/includes/gamma_correction.html
> +        <button type="submit">Camma Correction</button>
Βασικά δεν ήθελα να κάνω request changes, απλά να στο επισημάνω lol

2021-04-09 07:01 UTC, p18mili1 commented on templates/includes/gamma_correction.html
> +        <button type="submit">Camma Correction</button>
@sophia-ts  πολύ πρακτικό αυτό με το  regex, ωραία ιδέα,

2021-04-09 12:38 UTC, Stavrospanakakis commented
@sophia-ts Ενώ θα έπρεπε να παίρνει τιμές από 0.0 - 0.9 λόγω του regex, εμένα με αφήνει να βάζω ότι αριθμό θέλω

2021-04-09 12:39 UTC, Stavrospanakakis commented on static/js/gamma_correction.js
> +        console.log("Fetch")
Αυτά τα ```console.log``` δεν χρειάζεται να υπάρχουν.

2021-04-09 12:41 UTC, Stavrospanakakis requested changes

2021-04-09 12:41 UTC, Stavrospanakakis commented on static/js/gamma_correction.js
> +        console.log("Fetch")
Αυτά τα ```console.log``` δεν χρειάζεται να υπάρχουν.

2021-04-09 13:15 UTC, sophia-ts commented
> @sophia-ts Ενώ θα έπρεπε να παίρνει τιμές από 0.0 - 0.9 λόγω του regex, εμένα με αφήνει να βάζω ότι αριθμό θέλω

Fixed!

2021-04-09 14:05 UTC, dimpram approved these changes

2021-04-09 19:08 UTC, p18mili1 approved these changes

2021-04-12 10:58 UTC, dimpram commented
@Stavrospanakakis review?

2021-04-12 10:59 UTC, Stavrospanakakis approved these changes

2021-04-12 11:26 UTC, merged