Feature/upload image
Fotographia/fotographia-editor pull request #3
Opened 2021-03-11 13:42 UTC by Stavrospanakakis

## New functionallities 

- Add main template
- Add editor template
- Add upload image functionallity
- Uploading an image redirects user to the editor template
- Uploading a filename which is not an image returns error

## How it works

When user accesses home page he gets a unique session id. Server uses this id to create a unique folder to store his image. 
Example: /static/images/<session_id>/<image.png>.

When he uploads his image, server stores it at the path above. If image is in the correct form (jpg, jpeg, png) it redirects user to the editor, else, he throws an error.

2021-03-11 17:04 UTC, p18mili1 commented
Πολύ σωστό και λειτουργικό Σταύρο. Επιπλέον θα μπορούσε αντί για σκέτο μήνυμα σφάλματος να προτρέπει το χρήστη να δοκιμάσει ξανά. Ίσως να είναι προτιμότερο να μην κλείνει το session σε περίπτωση που ο χρήστης επέλεξε κατά λάθος, λάθος αρχείο.

2021-03-11 17:05 UTC, p18mili1 approved these changes
Πολύ σωστό και λειτουργικό Σταύρο. Επιπλέον θα μπορούσε αντί για σκέτο μήνυμα σφάλματος να προτρέπει το χρήστη να δοκιμάσει ξανά. Ίσως να είναι προτιμότερο να μην κλείνει το session σε περίπτωση που ο χρήστης επέλεξε κατά λάθος, λάθος αρχείο.

2021-03-11 18:53 UTC, dimpram commented
Sorry για την νουμπικη ερώτηση αλλά πως το τρέχεις? Γράφω python run.py και μου βγάζει error

2021-03-11 19:09 UTC, dimpram requested changes
Μου αρέσει πολύ η ιδέα. Κοιτάω ωστόσο παράλληλα και flask tutorials για να μπω λίγο στο mindset. Αυτά που σημείωσα είναι πολύ minor απλά έπρεπε να επισημανθούν

2021-03-11 19:09 UTC, dimpram commented on internal/__init__.py
> +import internal.views.upload_Image
οκ βρήκα το error, το `upload_Image` πρέπει να είναι `upload_image` αλλιώς δεν βρίσκει το module. Έχεις βάλει δηλαδή ένα κεφαλαίο I στο image

2021-03-11 19:09 UTC, dimpram commented on internal/static/js/uploadImage.js
> +var imageUploadInput = document.getElementById('imageUploadInput')
Προτείνω να χρησιμοποιούμε ES6 syntax όπου χρειάζεται γενικά οπότε ας αφήσουμε και τα vars πίσω αν συμφωνείτε. (δηλαδή να χρησιμοποιούμε let και const)

2021-03-12 10:58 UTC, Stavrospanakakis commented on internal/static/js/uploadImage.js
> +var imageUploadInput = document.getElementById('imageUploadInput')
Done. [b98b38f](https://github.com/Fotographia/fotographia-editor/pull/3/commits/b98b38f1ecfdb6d841af9b06dcc456327c65e541)

2021-03-12 10:58 UTC, Stavrospanakakis commented on internal/__init__.py
> +import internal.views.upload_Image
Done. [60dbd23](https://github.com/Fotographia/fotographia-editor/pull/3/commits/60dbd23156c6afbe7a8b5135e187b6ba19c31c2d)

2021-03-12 11:22 UTC, dimpram approved these changes

2021-03-12 14:12 UTC, sophia-ts approved these changes

2021-03-12 14:14 UTC, merged