Added feature edge-detection
Fotographia/fotographia-editor pull request #32
Opened 2021-04-13 16:30 UTC by dimpram

2021-04-13 17:17 UTC, Stavrospanakakis requested changes

2021-04-13 17:17 UTC, Stavrospanakakis commented on utils/edge_detection.py
> +    imsave(path, result, cmap=plt.get_cmap("gray"))
Γιατί το έκανες με matplotlib; Μπορείς να το κάνεις απευθείας με opencv με την ```cv2.imwrite(path, result)```

2021-04-13 17:35 UTC, sophia-ts requested changes
Μια μεγάλη παρατήρηση το [edge detection](https://en.wikipedia.org/wiki/Edge_detection) από όσο ξέρω αυτό που κάνει είναι πως αναδεικνύει τις ακμές, τα edges δηλαδή. Ενώ ο αλγόριθμος λειτουργεί κανονικά, το γκρι background που έχει όχι μόνο δεν αναδικνύει τις ακμές αλλά τις κάνει και πιο δύσκολο να τις δει κάποιος με γυμνό ματι. Δοκίμασε κάποια άλλη τεντική ή κάποια άλλη βιβλιοθήκη που να μπορεί να κάνει πιο διακριτά τα edges

Μου άρεσε πολύ το menu όπου επιλέγεις το φίλτρο

2021-04-13 19:08 UTC, dimpram commented on utils/edge_detection.py
> +    imsave(path, result, cmap=plt.get_cmap("gray"))
oops, είχα κάνει μια άλλη υλοποίηση στην αρχή και μάλλον το ξέχασα.

2021-04-13 19:12 UTC, dimpram commented
> Μια μεγάλη παρατήρηση το [edge detection](https://en.wikipedia.org/wiki/Edge_detection) από όσο ξέρω αυτό που κάνει είναι πως αναδεικνύει τις ακμές, τα edges δηλαδή. Ενώ ο αλγόριθμος λειτουργεί κανονικά, το γκρι background που έχει όχι μόνο δεν αναδικνύει τις ακμές αλλά τις κάνει και πιο δύσκολο να τις δει κάποιος με γυμνό ματι. Δοκίμασε κάποια άλλη τεντική ή κάποια άλλη βιβλιοθήκη που να μπορεί να κάνει πιο διακριτά τα edges

Στην πραγκατικότητα έτσι δουλεύουν αυτά τα φίτλρα. Τουλάχιστον όσο έχω δει. Έπειδη κάνουν composition συνήθως πολλών εικόνων με edges, καταλήγει να δημιουργείται αυτό το background με σκοπό να φαίνονται όσο το δυνατόν καλύτερα γίνεται όλα (από όσο έχω καταλάβει).

Στην περίπτωση που δεν φαίνονται καλά τα edges, σημαίνει πως η φωτογραφία εξαρχής δεν είχε κάποιο hard texture πάνω της.

2021-04-13 21:14 UTC, dimpram commented
@sophia-ts νομίζω τώρα είναι έτσι όπως λες.

2021-04-14 11:27 UTC, sophia-ts approved these changes
Τώρα ναι. Δουλεύει μια χαρά! Δοκίμασα και διάφορες εικόνες και όλα εντάξει

2021-04-14 16:07 UTC, Stavrospanakakis approved these changes

2021-04-15 13:36 UTC, p18mili1 approved these changes

2021-04-15 13:36 UTC, p18mili1 commented on utils/edge_detection.py
> +from matplotlib.image import imsave
Αυτές δεν τις χρησιμοποιείς, έτσι;  Απλά βγάλτες πριν κάνεις merge

2021-04-16 13:35 UTC, merged