Add threshold feature
Fotographia/fotographia-editor pull request #34
Opened 2021-04-14 11:52 UTC by sophia-ts

Closes: #24 

Added threshold feature. The user can select the threshold type from a drop down list, Available options:
`normal threshold`
`adaptive threshold`
`gaussian threshold`

Το έκανα από το σωστό branch τώρα όπως τόνησε και ο @dimpram

2021-04-14 12:09 UTC, dimpram approved these changes

2021-04-14 16:10 UTC, Stavrospanakakis requested changes

2021-04-14 16:10 UTC, Stavrospanakakis commented on utils/threshold.py
> +    cv2.imwrite(path, thres)
Καλό θα ήταν να διαγράφεις την προηγούμενη εικόνα πριν την κάνεις save.

2021-04-14 16:21 UTC, sophia-ts commented on utils/threshold.py
> +    cv2.imwrite(path, thres)
Done!

2021-04-15 10:37 UTC, Stavrospanakakis approved these changes

2021-04-15 13:47 UTC, p18mili1 approved these changes
Well done

2021-04-15 14:26 UTC, merged