Add pixelize feature
Fotographia/fotographia-editor pull request #36
Opened 2021-04-14 14:10 UTC by sophia-ts

Closes #35 

The user selects how many pixels he wants the image to be scaled down

2021-04-14 16:12 UTC, Stavrospanakakis requested changes

2021-04-14 16:12 UTC, Stavrospanakakis commented on utils/pixelize.py
> +    result.save(path)
Καλό θα ήταν να διαγράφεις την εικόνα πριν την κάνεις save.

2021-04-14 16:20 UTC, sophia-ts commented on utils/pixelize.py
> +    result.save(path)
Done!

2021-04-15 10:37 UTC, Stavrospanakakis approved these changes

2021-04-15 12:10 UTC, dimpram approved these changes

2021-04-16 13:35 UTC, dimpram approved these changes

2021-04-16 22:21 UTC, p18mili1 requested changes

2021-04-16 22:21 UTC, p18mili1 commented on app.py
>  @app.route("/api/edge-detection", methods=["POST"])
Έχει γίνει κάποιο μπέρδεμα εδώ. Θέλει διόρθωση

Κατά τ'άλλα είναι μια χαρά. Και το 200 είναι οκευ

2021-04-16 22:23 UTC, p18mili1 requested changes

2021-04-16 22:23 UTC, p18mili1 commented on app.py
>  @app.route("/api/edge-detection", methods=["POST"])
Έχει γίνει κάποιο μπέρδεμα εδώ. Θέλει διόρθωση

Κατά τ'άλλα είναι μια χαρά. Και το 200 είναι οκευ

2021-04-16 22:29 UTC, p18mili1 commented on app.py
Έχει γίνει κάποιο μπέρδεμα εδώ. Θέλει διόρθωση

> 

Κατά τ'άλλα είναι μια χαρά. Και το 200 είναι οκευ

2021-04-16 22:33 UTC, p18mili1 requested changes
Έχει γίνει κάποιο μπέρδεμα εδώ. Θέλει διόρθωση
line 184
@app.route("/api/edge-detection", methods=["POST"])
def feature_edge_detection():
  session_id = request.args.get("session_id")
  filename = request.args.get("filename")

  path = app.config["UPLOAD_FOLDER"] + "/" + session_id + "/" + filename

    session_id = request.args.get("session_id")
    filename = request.args.get("filename")


Κατά τ'άλλα είναι μια χαρά. Και το 200 είναι οκευ

2021-04-16 22:38 UTC, p18mili1 commented on app.py
> +
Έχει γίνει κάποιο μπέρδεμα εδώ. Θέλει διόρθωση

Κατά τ'άλλα είναι μια χαρά. Και το 200 είναι οκευ

2021-04-16 22:41 UTC, p18mili1 requested changes

2021-04-16 22:41 UTC, p18mili1 commented on app.py
> +
Έχει γίνει κάποιο μπέρδεμα εδώ. Θέλει διόρθωση

Κατά τ'άλλα είναι μια χαρά. Και το 200 είναι οκευ

2021-04-16 22:42 UTC, p18mili1 requested changes

2021-04-16 22:42 UTC, p18mili1 commented on app.py
> +  session_id = request.args.get("session_id")
Έχει γίνει κάποιο μπέρδεμα εδώ. Θέλει διόρθωση

Κατά τ'άλλα είναι μια χαρά. Και το 200 είναι οκευ

2021-04-17 13:40 UTC, sophia-ts commented
> Έχει γίνει κάποιο μπέρδεμα εδώ. Θέλει διόρθωση
> line 184
> @app.route("/api/edge-detection", methods=["POST"])
> def feature_edge_detection():
> session_id = request.args.get("session_id")
> filename = request.args.get("filename")
> 
> path = app.config["UPLOAD_FOLDER"] + "/" + session_id + "/" + filename
> 
> ```
> session_id = request.args.get("session_id")
> filename = request.args.get("filename")
> ```
> 
> Κατά τ'άλλα είναι μια χαρά. Και το 200 είναι οκευ

Έχεις απόλυτο δίκιο. Το έκανα καταλάθος όταν έφτιαχνα τα conflicts.

2021-04-17 14:49 UTC, p18mili1 commented
Μόνο αυτό ήταν.

2021-04-17 14:49 UTC, p18mili1 approved these changes

2021-04-19 09:23 UTC, merged